#!/usr/bin/env python3
"""
MCP Auth Testing Utility

This script provides utilities for testing the MCP authentication system.
It can create tokens with different scopes and test auth against MCP services.
"""

import sys
import os
import asyncio
from pathlib import Path

# Add the project root to Python path
PROJECT_ROOT = Path(__file__).parent
sys.path.insert(0, str(PROJECT_ROOT))

from core.agents.agent_sdk.auth import (
    create_token, 
    verify_capability, 
    get_service_token, 
    get_admin_token,
    create_dev_token,
    DEFAULT_SCOPES,
    AuthError
)

def print_token_info(token: str, description: str = ""):
    """Print token information for debugging."""
    print(f"\n{description}:")
    print(f"  Token: {token}")
    
    # Try to parse the token to show what it contains
    try:
        parts = token.split('.')
        if len(parts) == 2:
            payload = parts[0]
            timestamp_str, scope_str = payload.split(':', 1)
            scopes = scope_str.split(',') if scope_str else []
            print(f"  Scopes: {scopes}")
            print(f"  Timestamp: {timestamp_str}")
    except Exception as e:
        print(f"  Error parsing token: {e}")

def test_auth_scenarios():
    """Test various authentication scenarios."""
    print("=== MCP Authentication Test Scenarios ===\n")
    
    # Test 1: Service tokens
    print("1. Service Tokens:")
    for service in DEFAULT_SCOPES.keys():
        if service != "admin":
            token = get_service_token(service)
            print_token_info(token, f"{service} service token")
    
    # Test 2: Admin token
    print("\n2. Admin Token:")
    admin_token = get_admin_token()
    print_token_info(admin_token, "Admin token")
    
    # Test 3: Custom dev tokens
    print("\n3. Custom Development Tokens:")
    read_only_token = create_dev_token("read")
    print_token_info(read_only_token, "Read-only token")
    
    write_token = create_dev_token("read,write")
    print_token_info(write_token, "Read/write token")
    
    # Test 4: Verify capabilities
    print("\n4. Capability Verification Tests:")
    
    test_cases = [
        (admin_token, "read", "Admin token should have read access"),
        (admin_token, "write", "Admin token should have write access"),
        (admin_token, "propose", "Admin token should have propose access"),
        (read_only_token, "read", "Read-only token should have read access"),
        (read_only_token, "write", "Read-only token should NOT have write access"),
        ("invalid_token", "read", "Invalid token should be rejected"),
        ("", "read", "Empty token should be rejected"),
    ]
    
    for token, scope, description in test_cases:
        try:
            verify_capability(token, scope)
            print(f"  ✓ PASS: {description}")
        except AuthError as e:
            if "should NOT" in description or "should be rejected" in description:
                print(f"  ✓ PASS: {description} - {e}")
            else:
                print(f"  ✗ FAIL: {description} - {e}")
        except Exception as e:
            print(f"  ✗ ERROR: {description} - {e}")

async def test_mcp_service_auth():
    """Test auth against actual MCP services (if running)."""
    print("\n=== Testing MCP Service Authentication ===\n")
    
    # Test tokens for different services
    alert_token = get_service_token("alert_service")
    data_token = get_service_token("data_collector") 
    price_token = get_service_token("price_optimizer")
    admin_token = get_admin_token()
    
    print(f"Alert service token: {alert_token}")
    print(f"Data collector token: {data_token}")
    print(f"Price optimizer token: {price_token}")
    print(f"Admin token: {admin_token}")
    
    print("\nTo test with actual MCP servers:")
    print("1. Start an MCP server (e.g., python -m core.agents.alert_service.mcp_server)")
    print("2. Use these tokens as the 'capability_token' parameter in MCP calls")
    print("3. Test various combinations to verify auth is working")

def create_test_tokens():
    """Create a set of test tokens for development."""
    print("\n=== Creating Test Tokens for Development ===\n")
    
    tokens = {
        "admin": get_admin_token(),
        "alert_service": get_service_token("alert_service"),
        "data_collector": get_service_token("data_collector"),
        "price_optimizer": get_service_token("price_optimizer"),
        "read_only": create_dev_token("read"),
        "read_write": create_dev_token("read,write"),
    }
    
    # Write tokens to a file for easy access during development
    token_file = PROJECT_ROOT / "test_tokens.txt"
    with open(token_file, 'w') as f:
        f.write("# MCP Test Tokens - Generated by auth test utility\n")
        f.write("# Use these tokens for testing MCP service authentication\n\n")
        
        for name, token in tokens.items():
            f.write(f"{name.upper()}_TOKEN={token}\n")
        
        f.write("\n# Usage examples:\n")
        f.write("# - Use ADMIN_TOKEN for full access to all services\n")
        f.write("# - Use service-specific tokens to test scoped access\n")
        f.write("# - Use READ_ONLY_TOKEN to test read-only access\n")
        
    print(f"Tokens written to: {token_file}")
    print("\nToken Summary:")
    for name, token in tokens.items():
        print(f"  {name}: {token[:32]}...")

def main():
    """Main test function."""
    if len(sys.argv) > 1:
        command = sys.argv[1]
        if command == "test":
            test_auth_scenarios()
        elif command == "mcp":
            asyncio.run(test_mcp_service_auth())
        elif command == "tokens":
            create_test_tokens()
        else:
            print("Unknown command. Use: test, mcp, or tokens")
    else:
        print("MCP Auth Testing Utility")
        print("Usage:")
        print("  python test_auth.py test    - Run authentication test scenarios")
        print("  python test_auth.py mcp     - Test with MCP services")
        print("  python test_auth.py tokens  - Create test tokens for development")

if __name__ == "__main__":
    main()