import { Dialog, DialogContent, DialogHeader, DialogTitle } from './ui/dialog'
import { Button } from './ui/button'

interface Incident {
  id: string
  rule_id: string
  sku: string
  status: 'OPEN' | 'ACKED' | 'RESOLVED'
  first_seen: string
  last_seen: string
  severity: 'info' | 'warn' | 'crit'
  title: string
}

const SEVERITY_CONFIG = {
  info: { bg: 'bg-blue-500/20', text: 'text-blue-400', label: 'Info', icon: 'ℹ️' },
  warn: { bg: 'bg-yellow-500/20', text: 'text-yellow-400', label: 'Warning', icon: '⚠️' },
  crit: { bg: 'bg-red-500/20', text: 'text-red-400', label: 'Critical', icon: '🚨' },
}

const STATUS_CONFIG = {
  OPEN: { bg: 'bg-red-500/20', text: 'text-red-400', label: 'Open' },
  ACKED: { bg: 'bg-yellow-500/20', text: 'text-yellow-400', label: 'Acknowledged' },
  RESOLVED: { bg: 'bg-green-500/20', text: 'text-green-400', label: 'Resolved' },
}

interface AlertDetailModalProps {
  incident: Incident | null
  open: boolean
  onOpenChange: (open: boolean) => void
  onAcknowledge: (id: string) => void
  onResolve: (id: string) => void
}

export function AlertDetailModal({
  incident,
  open,
  onOpenChange,
  onAcknowledge,
  onResolve,
}: AlertDetailModalProps) {
  if (!incident) return null

  const severity = SEVERITY_CONFIG[incident.severity]
  const status = STATUS_CONFIG[incident.status]
  const isLLM = incident.rule_id === 'llm_agent'

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <span className="text-2xl">{severity.icon}</span>
            <span>{incident.title}</span>
            {isLLM && (
              <div className="inline-flex items-center gap-1 px-2 py-1 rounded-full bg-purple-500/30 text-purple-300 text-sm font-medium border border-purple-400/30">
                <span>🤖</span>
                <span>AI Generated</span>
              </div>
            )}
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <div className="text-xs text-muted-foreground mb-1">SKU</div>
              <div className="font-mono text-sm">{incident.sku}</div>
            </div>
            <div>
              <div className="text-xs text-muted-foreground mb-1">Status</div>
              <div
                className={`inline-flex px-2 py-1 rounded text-xs font-medium ${status.bg} ${status.text}`}
              >
                {status.label}
              </div>
            </div>
            <div>
              <div className="text-xs text-muted-foreground mb-1">Severity</div>
              <div
                className={`inline-flex px-2 py-1 rounded text-xs font-medium ${severity.bg} ${severity.text}`}
              >
                {severity.label}
              </div>
            </div>
            <div>
              <div className="text-xs text-muted-foreground mb-1">Rule ID</div>
              <div className="font-mono text-xs">{incident.rule_id}</div>
            </div>
          </div>

          <div className="border-t pt-4">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <div className="text-xs text-muted-foreground mb-1">First Seen</div>
                <div className="text-sm">{new Date(incident.first_seen).toLocaleString()}</div>
              </div>
              <div>
                <div className="text-xs text-muted-foreground mb-1">Last Seen</div>
                <div className="text-sm">{new Date(incident.last_seen).toLocaleString()}</div>
              </div>
            </div>
          </div>

          {isLLM && (
            <div className="border-t pt-4">
              <div className="text-sm text-muted-foreground mb-2">
                This alert was generated by the AI Agent analyzing pricing anomalies and market
                conditions.
              </div>
            </div>
          )}

          {incident.status === 'OPEN' && (
            <div className="flex gap-2 pt-4 border-t">
              <Button
                onClick={() => {
                  onAcknowledge(incident.id)
                  onOpenChange(false)
                }}
                variant="outline"
                className="flex-1"
              >
                Acknowledge
              </Button>
              <Button
                onClick={() => {
                  onResolve(incident.id)
                  onOpenChange(false)
                }}
                className="flex-1"
              >
                Resolve
              </Button>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  )
}
